steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - apps/api/Dockerfile
      - --tag
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/oshikatsu/oshikatsu-api:$BUILD_ID
      - .
images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/oshikatsu/oshikatsu-api:$BUILD_ID
options:
  logging: CLOUD_LOGGING_ONLY